version: "3.8"


services:

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33306:3306"
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    env_file:
      - ../.env


