version: "3.8"

services:

  nginx:
    image: library/nginx:alpine
    container_name: nds_nginx
    ports:
      - 80:80
    volumes:
      - static-volume:/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - web
  web:
    image: kairick/nds
    container_name: nds_web
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 crm.wsgi:application
    extra_hosts:
      - "host.docker.internal:172.18.0.1"

    volumes:
      - static-volume:/app/crm/static

volumes:
  static-volume:

networks:
  default:
    name: nds-network