version: "3.8"


services:

  db:
    env_file:
    - .env
    environment:
    - MYSQL_DATABASE
    - MYSQL_USER
    - MYSQL_ROOT_PASSWORD
    - MYSQL_PORT
    image: mysql
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql
  nginx:
    image: library/nginx:alpine
    ports:
    - 80:80
    volumes:
    - ./media:/media
    - static-volume:/static
    - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
    - web
  web:
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 crm.wsgi:application
    depends_on:
    - db
    image: kairick/nds
    volumes:
      - static-volume:/usr/crm/app/static
volumes:
  static-volume:


networks:
  default:
    name: nds-network