version: "3.8"

services:

  nginx:
    image: library/nginx:alpine
    container_name: nds_nginx
    ports:
      - 80:80
    volumes:
      - /var/www/html/crm_build/crm/static:/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/apache2/.htpasswd:/etc/apache2/.htpasswd

  web:
    image: kairick/nds
    container_name: nds_web
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 crm.wsgi:application
    extra_hosts:
      - "host.docker.internal:172.18.0.1"

    volumes:
      - /var/www/html/crm_build/crm/static:/app/crm/staticdir

volumes:
  static-volume:
    driver: local

networks:
  default:
    name: nds-network