version: "3.8"

services:

  db:
    image: mysql
    container_name: nds_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 33306:3306
    volumes:
    - db_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
      -
  nginx:
    image: library/nginx:alpine
    container_name: nds_nginx
    ports:
    - 80:80
    volumes:
    - ./media:/media
    - static-volume:/static
    - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
    - web
  web:
    image: kairick/nds
    container_name: nds_web
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 crm.wsgi:application
    depends_on:
    - db

    volumes:
      - static-volume:/usr/app/crm/static

volumes:
  db_data: {}
  static-volume:

networks:
  default:
    name: nds-network