name: Build
on:
  push:
    branches:
      - main
      - deploy_static

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: dockerfile add env
        run: python docker_update.py '${{secrets.SECRET_KEY}}' ${{secrets.DB_NAME}} ${{secrets.DB_USER}} '${{secrets.DB_PASSWORD}}'
      - name: docker build
        run: docker build . -t kairick/nds
      - name: push Docker img
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kairick/nds
          registry: docker.io
          tag: latest
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Publish
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         port: ${{ secrets.SSH_PORT }}
         source: "docker-compose.yml, nginx.conf"
         target: "."  
     
      - name: ssh remote docker pull and run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker-compose pull
            docker-compose -f docker-compose.yml up -d
      - name: get migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker-compose exec -T web cp -r static/* staticdir/
            docker-compose exec -T web python manage.py collectstatic --noinput
            docker-compose exec -T web python manage.py migrate
